const IconsPath = '../assets/icons'
export enum Icons {
  splash_image = require(`${IconsPath}/splash_mepco.png`),
  pitc_logo = require(`${IconsPath}/pitc_logo.png`),
  meter_icon = require(`${IconsPath}/meter.png`),
  drop_down = require(`${IconsPath}/dropdown.png`),
  purchase_slip = require(`${IconsPath}/bill.png`),
  off_peak_icon = require(`${IconsPath}/up.png`),
  peak_icon = require(`${IconsPath}/down.png`),
  menu = require(`${IconsPath}/menu.png`),

  ic_tick = require(`${IconsPath}/ic_tick.png`),
  ic_mepco = require(`${IconsPath}/ic_mepco.png`),
  ic_splashLogo = require(`${IconsPath}/ic_splashLogo.png`),
  ic_usaid = require(`${IconsPath}/ic_usaid.png`),
  ic_pitc = require(`${IconsPath}/ic_pitc.png`),

  ic_eye = require(`${IconsPath}/eye_icon.png`),
  ic_eyeDisable = require(`${IconsPath}/eye_hidden_icon.png`),
  ic_cross = require(`${IconsPath}/ic_cross.png`),

  ic_home = require(`${IconsPath}/ic_home.png`),
  ic_services = require(`${IconsPath}/ic_services.png`),
  ic_invite = require(`${IconsPath}/ic_invite.png`),
  ic_settings = require(`${IconsPath}/ic_settings.png`),
  ic_message = require(`${IconsPath}/ic_message.png`),

  ic_pin = require(`${IconsPath}/ic_pin.png`),
  ic_downArrow = require(`${IconsPath}/ic_dowmArrow.png`),
  ic_mainMenu = require(`${IconsPath}/ic_mainMenu.png`),
  ic_bell = require(`${IconsPath}/ic_bell.png`),

  ic_normalMeter = require(`${IconsPath}/ic_threePhase.png`),
  // ic_threephaseMeter = require(`${IconsPath}/ic_threePhase.png`),
  ic_smartMeter = require(`${IconsPath}/ic_bell.png`),
  ic_rightArrow = require(`${IconsPath}/ic_rightArrow.png`),
  ic_right = require(`${IconsPath}/ic_rightArrow.png`),
  ic_plus = require(`${IconsPath}/ic_plus.png`),
  logo = require(`${IconsPath}/logo.png`),
  smart_monitoring = require(`${IconsPath}/smartmonitoringicon.png`),
  smart_advisor = require(`${IconsPath}/smartenergyadvisoricon.png`),
  power_outage = require(`${IconsPath}/poweroutageicon.png`),
  smart_payment = require(`${IconsPath}/smartpaymentsicon.png`),
  load_management = require(`${IconsPath}/loadmanagementscheduleicon.png`),
  customer_service = require(`${IconsPath}/customerservicesicon.png`),
  user_icon = require(`${IconsPath}/user_icon.png`),
  email_icon = require(`${IconsPath}/email_icon.png`),
  password_icon = require(`${IconsPath}/password__icon.png`),
  cnic_icon = require(`${IconsPath}/cnic_icon.png`),
  phone_icon = require(`${IconsPath}/call_icon.png`),
  ic_peak = require(`${IconsPath}/ic_Peak.png`),
  ic_Offpeak = require(`${IconsPath}/ic_Offpeak.png`),
  ic_edit = require(`${IconsPath}/ic_edit.png`),
  ic_easypaisa = require(`${IconsPath}/ic_easypaisa.png`),
  ic_jazzcash = require(`${IconsPath}/ic_jazzcash.png`),
  ic_nayapay = require(`${IconsPath}/ic_nayapay.png`),
  ic_sadapay = require(`${IconsPath}/ic_sadapay.png`),
  ic_raast = require(`${IconsPath}/ic_raast.png`),
  ic_omni = require(`${IconsPath}/ic_omni.png`),
  ic_credit = require(`${IconsPath}/ic_credit.png`),
  ic_bank = require(`${IconsPath}/ic_bank.png`),
  ic_google = require(`${IconsPath}/google_icon.png`),
  ic_fb = require(`${IconsPath}/facebook_icon.png`),
  ic_back = require(`${IconsPath}/back_icon.png`),
  ic_mobile = require(`${IconsPath}/mobile_fp_icon.png`),
  ic_addIcon = require(`${IconsPath}/ic_addIcon.png`),
  ic_email_fp = require(`${IconsPath}/email_fp_icon.png`),
  ic_dot_icon = require(`${IconsPath}/ic_dot_icon.png`),
  ic_normal_meter = require(`${IconsPath}/ic_normal_meter.png`),
  ic_smart_meter = require(`${IconsPath}/ic_smart_meter.png`),
  ic_delete_icon = require(`${IconsPath}/ic_deled.png`),
  ic_star_icon = require(`${IconsPath}/ic_star_icon.png`),
  ic_refno = require(`${IconsPath}/ic_refno.png`),

  ic_deleteMeterIcon = require(`${IconsPath}/ic_deleteMeterIcon.jpg`),
  ic_starGreyIcon = require(`${IconsPath}/star_grey_icon.png`),
  ic_starWhiteIcon = require(`${IconsPath}/star_white_icon.png`),

  ic_location = require(`${IconsPath}/location.png`),
  ic_MeterIcon = require(`${IconsPath}/meteicon.png`),
  ic_connection = require(`${IconsPath}/ic_connection.png`),
  ic_loadProfile = require(`${IconsPath}/load_profile_icon.png`),
  ic_consumption = require(`${IconsPath}/consumptions_icon.png`),
  ic_smartPayment = require(`${IconsPath}/smart_payment_icon.png`),
  ic_powerOutage = require(`${IconsPath}/outage_icon.png`),
  ic_energyAdvisor = require(`${IconsPath}/energy_advisor_icon.png`),
  ic_unitDetail = require(`${IconsPath}/unit_details_icon.png`),
  ic_close_icon = require(`${IconsPath}/close_icon.png`),
  ic_transformer = require(`${IconsPath}/transformer_icon.png`),
  ic_list = require(`${IconsPath}/list_icon.png`),
  ic_grid = require(`${IconsPath}/grid_icon.png`),

  ic_white_Three_Phase = require(`${IconsPath}/white_three_Phase.png`),

  ic_link = require(`${IconsPath}/link.png`),
  ic_rightIcons = require(`${IconsPath}/arrow_right_icon.png`),

  ic_appIcon =  require(`${IconsPath}/appIcon.png`),
  ic_faceBook = require(`${IconsPath}/facebook_icon.png`),

  ic_download = require(`${IconsPath}/download.png`),
  ic_youtubeIcon = require(`${IconsPath}/youtubeIcon.png`),
  ic_facebook = require(`${IconsPath}/facebookIcons.png`),
  ic_instagram = require(`${IconsPath}/instagramIcon.png`),

 
  
  

}


